version: "3.1"

services:


  task-tracker-backend:
    container_name: "task-tracker-backend"
    image: task-tracker-backend:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    container_name: "postgres"
    image: postgres:14.7-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: task-tracker-backend
    ports:
      - "15432:5432"






