spring:
  application:
    name: task-tracker-backend

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/task-tracker-backend
    username: admin
    password: admin

  flyway:
    url: jdbc:postgresql://localhost:15432/task-tracker-backend
    user: admin
    password: admin
    schemas: admin

jwt:
  token:
    secret-key: AB1EAF0F3A22AB268424E93CC4162A1CB29283F7513337CE950BA3A372E7262E
    life-time: 1600000
