CREATE TABLE users
(

    id                   BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email                VARCHAR(50) NOT NULL UNIQUE,
    password             VARCHAR(50) NOT NULL,
    date_of_registration DATE        not null DEFAULT CURRENT_DATE,
    first_name           VARCHAR(50) NOT NULL

);

CREATE TYPE ROLE AS ENUM ('USER', 'ADMIN');


CREATE TABLE user_roles
(

    id        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id   SERIAL REFERENCES users (id),
    user_role ROLE NOT NULL DEFAULT 'USER'

)